export const API_BASE = "https://norma.nomoreparties.space/api";

export const RESET_FORM_FAILED: "RESET_FORM_FAILED" = "RESET_FORM_FAILED";
export const RESET_FORM_SUCCESS: "RESET_FORM_SUCCESS" = "RESET_FORM_SUCCESS";
export const UPDATE_FORM_FAILED: "UPDATE_FORM_FAILED" = "UPDATE_FORM_FAILED";
export const UPDATE_FORM_SUCCESS: "UPDATE_FORM_SUCCESS" = "UPDATE_FORM_SUCCESS";

export const REGISTER_FORM_SUCCESS: "REGISTER_FORM_SUCCESS" = "REGISTER_FORM_SUCCESS";
export const REGISTER_FORM_FAILED: "REGISTER_FORM_FAILED" = "REGISTER_FORM_FAILED";

export const LOGIN_FORM_SUCCESS: "LOGIN_FORM_SUCCESS" = "LOGIN_FORM_SUCCESS";
export const LOGIN_FORM_FAILED: "LOGIN_FORM_FAILED" = "LOGIN_FORM_FAILED";
export const LOGOUT_FORM_SUCCESS: "LOGOUT_FORM_SUCCESS" = "LOGOUT_FORM_SUCCESS";
export const LOGOUT_FORM_FAILED: "LOGOUT_FORM_FAILED" = "LOGOUT_FORM_FAILED";

export const SET_USER_SUCCESS: "SET_USER_SUCCESS" = "SET_USER_SUCCESS";
export const SET_USER_FAILED: "SET_USER_FAILED" = "SET_USER_FAILED";

export const AUTH_CHECK: "AUTH_CHECK" = "AUTH_CHECK";

export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT: "REMOVE_INGREDIENT" = "REMOVE_INGREDIENT";
export const GET_INGREDIENTS: "GET_INGREDIENTS" = "GET_INGREDIENTS";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" = "GET_INGREDIENTS_FAILED";
export const SET_ACTIVE_INGREDIENT: "SET_ACTIVE_INGREDIENT" = "SET_ACTIVE_INGREDIENT";

export const SET_CURRENT_TAB: "SET_CURRENT_TAB" = "SET_CURRENT_TAB";

export const ADD_BUN: "ADD_BUN" = "ADD_BUN";

export const INCREASE_INGREDIENT: "INCREASE_INGREDIENT" = "INCREASE_INGREDIENT";
export const DRAG_CONSTRUCTOR_INGREDIENTS: "DRAG_CONSTRUCTOR_INGREDIENTS" = "DRAG_CONSTRUCTOR_INGREDIENTS";
export const DRAG_BUN_INGREDIENT: "DRAG_BUN_INGREDIENT" = "DRAG_BUN_INGREDIENT";
export const SORT_INGREDIENTS_ON_DRAG: "SORT_INGREDIENTS_ON_DRAG" = "SORT_INGREDIENTS_ON_DRAG";

export const CLEAR_CONSTRUCTOR: "CLEAR_CONSTRUCTOR" = "CLEAR_CONSTRUCTOR";

export const CLOSE_MODAL: "CLOSE_MODAL" = "CLOSE_MODAL";
export const OPEN_INGREDIENTS_MODAL: "OPEN_INGREDIENTS_MODAL" = "OPEN_INGREDIENTS_MODAL";
export const OPEN_ORDER_MODAL: "OPEN_ORDER_MODAL" = "OPEN_ORDER_MODAL";
export const OPEN_CARD_MODAL: "OPEN_CARD_MODAL" = "OPEN_CARD_MODAL";
export const OPEN_CARD_ORDER_MODAL: "OPEN_CARD_ORDER_MODAL" = "OPEN_CARD_ORDER_MODAL";

export const POST_ORDER_INFO_SUCCESS: "POST_ORDER_INFO_SUCCESS" = "POST_ORDER_INFO_SUCCESS";
export const POST_ORDER_INFO_FAILED: "POST_ORDER_INFO_FAILED" = "POST_ORDER_INFO_FAILED";

export const FEED_CONNECT: "FEED_CONNECT" = "FEED_CONNECT";
export const FEED_DISCONNECT: "FEED_DISCONNECT" = "FEED_DISCONNECT";
export const FEED_CONNECTING: "FEED_CONNECTING" = "FEED_CONNECTING";
export const FEED_OPEN: "FEED_OPEN" = "FEED_OPEN";
export const FEED_CLOSE: "FEED_CLOSE" = "FEED_CLOSE";
export const FEED_MESSAGE: "FEED_MESSAGE" = "FEED_MESSAGE";
export const FEED_ERROR: "FEED_ERROR" = "FEED_ERROR";
export const FEED_CURRENT_ORDER: "FEED_CURRENT_ORDER" = "FEED_CURRENT_ORDER";

export const FEED_ORDER_CONNECT: "FEED_ORDER_CONNECT" = "FEED_ORDER_CONNECT";
export const FEED_ORDER_DISCONNECT: "FEED_ORDER_DISCONNECT" = "FEED_ORDER_DISCONNECT";
export const FEED_ORDER_CONNECTING: "FEED_ORDER_CONNECTING" = "FEED_ORDER_CONNECTING";
export const FEED_ORDER_OPEN: "FEED_ORDER_OPEN" = "FEED_ORDER_OPEN";
export const FEED_ORDER_CLOSE: "FEED_ORDER_CLOSE" = "FEED_ORDER_CLOSE";
export const FEED_ORDER_MESSAGE: "FEED_ORDER_MESSAGE" = "FEED_ORDER_MESSAGE";
export const FEED_ORDER_ERROR: "FEED_ORDER_ERROR" = "FEED_ORDER_ERROR";
export const FEED_ORDER_CURRENT_ORDER: "FEED_ORDER_CURRENT_ORDER" = "FEED_ORDER_CURRENT_ORDER";

export const GET_ORDER: "GET_ORDER" = "GET_ORDER";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";